# syntax=docker/dockerfile:1

ARG PY_V=3.13
ARG ZOU_FOLDER=/zou-dev

FROM python:${PY_V}-slim AS builder
USER root

RUN apt update \
    && apt install -y --no-install-recommends make python3-dev gcc g++ \
    && apt autoclean \
    && rm -rf /var/lib/apt/lists/*

ARG PY_V
ARG ZOU_FOLDER

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,rw,source=./zou-dev,target=$ZOU_FOLDER \
    pip install --upgrade pip wheel setuptools \
    && cd $ZOU_FOLDER \
    && pip install -e . \
    && python setup.py egg_info --egg-base=/usr/local/lib/python${PY_V}/site-packages

FROM python:${PY_V}-slim

LABEL org.opencontainers.image.authors="Mathieu Bouzard <mathieu.bouzard@gmail.com>"
LABEL org.opencontainers.image.source="https://gitlab.com/mathbou/docker-cgwire/-/tree/zou"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.title="Zou"

USER root

RUN apt update \
    && apt install -y --no-install-recommends curl ffmpeg bzip2 postgresql-client \
    && apt autoclean \
    && rm -rf /var/lib/apt/lists/*

ARG PY_V

COPY --from=builder /usr/local/lib/python${PY_V} /usr/local/lib/python${PY_V}
COPY --from=builder /usr/local/bin /usr/local/bin

ARG ZOU_FOLDER


ENV DEBUG 1
ENV MAIL_DEBUG 1
ENV FLASK_DEBUG 1
ENV FLASK_APP zou.app

WORKDIR ${ZOU_FOLDER}

COPY ./zou/init_zou.sh /init_zou.sh
COPY ./zou/upgrade_zou.sh /upgrade_zou.sh