# syntax=docker/dockerfile:1.4

ARG NODE_V=24
FROM node:${NODE_V}-slim

LABEL org.opencontainers.image.authors="Mathieu Bouzard <mathieu.bouzard@gmail.com>"
LABEL org.opencontainers.image.source="https://gitlab.com/mathbou/docker-cgwire/-/tree/kitsu"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.title="Kitsu"

WORKDIR /app

RUN apt update &&\
    apt install --yes --no-install-recommends git openssh-client ca-certificates &&\
    rm -rf /var/lib/apt/lists/*

COPY ./kitsu-dev/*.?* ./

ENV NPM_CACHE_FOLDER=/root/.npm
RUN --mount=type=cache,id=npm,target=$NPM_CACHE_FOLDER \
    `cp -rf $NPM_CACHE_FOLDER/package-lock.json . || true` &&\
    npm install --prefer-offline &&\
    cp -rf package-lock.json $NPM_CACHE_FOLDER

RUN sed -i 's/server: {/server: {watch: {usePolling: true},/' vite.config.js

CMD ["npm", "run", "dev", "--", "--host", "--debug", "--port", "8080"]